stages:
  - production

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_images:
  image: docker/compose:latest
  stage: production
  only:
    - master
  script:
    - ./build/run-build
    - ./build/run
  tags:
    - production
