version: "3.6"

networks:
  default:
    external:
      name: network

services:
  vk-group-backend:
    container_name: vk-group-backend
    build:
      context: .
      dockerfile: ./build/nodejs/Dockerfile
    restart: "always"
    image: registry.gitlab.com/aliasgame/vk-group-backend:node_14
    env_file: ./build/.env.list
