version: "3.6"

networks:
  default:
    external:
      name: ttfb

services:
  vk-group-backend:
    restart: "no"
    networks:
      default:
        aliases:
          - group.lc
    labels:
      - traefik.enable=true
      - traefik.http.routers.group.rule=Host(`group.lc`)
      - traefik.http.routers.group.entrypoints=web
      