version: "3.6"

networks:
  default:
    external:
      name: network

services:
  vk-groups-backend:
    container_name: vk-groups-backend
    build:
      context: .
      dockerfile: ./build/nodejs/Dockerfile
    restart: "always"
    image: registry.gitlab.com/aliasgame/vk-groups-backend:node_14
    env_file: ./build/.env.list
